CRUD_EMPLEADOS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplications.empleados.urls')),
    path('', include('aplications.departamento.urls')),
    path('', include('aplications.home.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplications/departamento/urls.py
from django.urls import path
from . import views


app_name = "departamento_app"

urlpatterns = [
    path('departments/', views.DepartamentoListView.as_view(), name = 'departamentos'),
    path('detail/<str:dep>/', views.EmpleadoDetailListView.as_view(), name = 'detail_dep')
    
]

aplications/empleados/urls.py
from django.urls import path
from . import views

app_name = "persona_app"



urlpatterns = [
    path('', views.Home_page.as_view(), name = 'home'),
    path('all/',views.listAll.as_view() ,name='list_all'),
    path('filter-Employe/', views.filterEmploye.as_view(), name = 'filtrar'),
    path('employe/<int:pk>', views.empleadoDetailView.as_view(), name = 'detail'),
    path('edit/<int:pk>/', views.EmpleadoUpdateView.as_view(), name = 'editar'),
    path('delete/<int:pk>', views.eliminar_empleado, name = 'eliminar'),
    path('crear/', views.EmpleadoCreateView.as_view(), name = 'crear'),
    path('email/',views.email, name = 'email')
]

templates/includes/footer.html
{% load static %}

<footer class="bg-light text-dark pt-5 pb-4 mt-5">
    <div class="container text-center text-md-start">
        <div class="row text-center text-md-start">
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">

                <h5 class="text-uppercase mb-4 font-weight-bold text-primary">
                    Nosotros
                </h5>
                <hr class="mb-4">
                <p>
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Asperiores, dolores dolorum. Quas sequi praesentium dicta eius provident recusandae nisi unde error possimus vero, aliquam explicabo, nihil odio necessitatibus nobis vel.
                </p>

            </div>

            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">

                <h5 class="text-uppercase mb-4 font-weight-bold text-primary">
                    Dejanos ayudarte
                </h5>
                <hr class="mb-4">
                <p>
                    <a class="text-dark" href="#">
                        Tú cuenta
                    </a>
                </p>
                <p>
                    <a class="text-dark" href="#">
                        Panel de administración
                    </a>
                </p>
                <p>
                    <a class="text-dark" href="#">
                        Ayuda
                    </a>
                </p>

            </div>

            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">

                <h5 class="text-uppercase mb-4 font-weight-bold text-primary">
                    Has dinero
                </h5>
                <hr class="mb-4">
                <p>
                    <a class="text-dark" href="#">
                        Vende productos
                    </a>
                </p>
                <p>
                    <a class="text-dark" href="#">
                        Afiliate
                    </a>
                </p>
                <p>
                    <a class="text-dark" href="#">
                        Anuncios
                    </a>
                </p>

            </div>

            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">

                <h5 class="text-uppercase mb-4 font-weight-bold text-primary">
                    Contactame
                </h5>
                <hr class="mb-4">
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                        <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5Z"/>
                    </svg>
                    Bogotá, Colombia
                    
                </p>

                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-at-fill" viewBox="0 0 16 16">
                        <path d="M2 2A2 2 0 0 0 .05 3.555L8 8.414l7.95-4.859A2 2 0 0 0 14 2H2Zm-2 9.8V4.698l5.803 3.546L0 11.801Zm6.761-2.97-6.57 4.026A2 2 0 0 0 2 14h6.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.606-3.446l-.367-.225L8 9.586l-1.239-.757ZM16 9.671V4.697l-5.803 3.546.338.208A4.482 4.482 0 0 1 12.5 8c1.414 0 2.675.652 3.5 1.671Z"/>
                        <path d="M15.834 12.244c0 1.168-.577 2.025-1.587 2.025-.503 0-1.002-.228-1.12-.648h-.043c-.118.416-.543.643-1.015.643-.77 0-1.259-.542-1.259-1.434v-.529c0-.844.481-1.4 1.26-1.4.585 0 .87.333.953.63h.03v-.568h.905v2.19c0 .272.18.42.411.42.315 0 .639-.415.639-1.39v-.118c0-1.277-.95-2.326-2.484-2.326h-.04c-1.582 0-2.64 1.067-2.64 2.724v.157c0 1.867 1.237 2.654 2.57 2.654h.045c.507 0 .935-.07 1.18-.18v.731c-.219.1-.643.175-1.237.175h-.044C10.438 16 9 14.82 9 12.646v-.214C9 10.36 10.421 9 12.485 9h.035c2.12 0 3.314 1.43 3.314 3.034v.21Zm-4.04.21v.227c0 .586.227.8.581.8.31 0 .564-.17.564-.743v-.367c0-.516-.275-.708-.572-.708-.346 0-.573.245-.573.791Z"/>
                    </svg>
                    nicovalbuena2011@gmail.com                       
                </p>

                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-outbound-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511zM11 .5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V1.707l-4.146 4.147a.5.5 0 0 1-.708-.708L14.293 1H11.5a.5.5 0 0 1-.5-.5z"/>
                    </svg>
                    +57-3224697945
                </p>

                
            </div>
            
            <hr class="mb-4">

            
            
            <div class="text-center">
                
                <div class="text-center-mb-2">

                    <p>
                        Copyright todos los derechos reservados
                        <a href="#">
                            <strong class="text-primary">
                                Nicolas Jimenez Valbuena
                            </strong>
                        </a>
                    </p>

                </div>    
                <ul class="list-unstyled list-inline">
                    <li class="list-inline-item">
                        <a href="#" class="text-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                                <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
                              </svg>
                        </a>
                    </li>

                    <li class="list-inline-item">
                        <a href="#" class="text-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                                <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                              </svg>
                        </a>
                    </li>

                    <li class="list-inline-item">
                        <a href="#" class="text-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                                <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
                              </svg>
                        </a>
                    </li>

                </ul>
            </div>

        </div>
    </div>
</footer>

templates/includes/nav.html
{% load static %}
<nav class="navbar navbar-expand-md bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'persona_app:home' %}">
        <img src="{% static 'img/devicon.png' %}" style="width: 50px; height: 50px;" alt="devicon">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'persona_app:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'persona_app:list_all' %}">Empleados</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'departamento_app:departamentos' %}" >Departamentos</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" aria-disabled="true">Administrar</a>
          </li> -->
        </ul>

        <a href="{% url 'persona_app:crear' %}">

          <button class="btn btn-outline-success" >Registrar Empleado</button>
        </a>
      </div>
    </div>
</nav>