CRUD_EMPLEADOS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplications.empleados.urls')),
    path('', include('aplications.departamento.urls')),
    path('', include('aplications.home.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplications/departamento/urls.py
from django.urls import path
from . import views


app_name = "departamento_app"

urlpatterns = [
    path('departments/', views.DepartamentoListView.as_view(), name = 'departamentos'),
    path('detail/<str:dep>/', views.EmpleadoDetailListView.as_view(), name = 'detail_dep')
    
]

aplications/empleados/urls.py
from django.urls import path
from . import views

app_name = "persona_app"



urlpatterns = [
    path('', views.Home_page.as_view(), name = 'home'),
    path('all/',views.listAll.as_view() ,name='list_all'),
    path('filter-Employe/', views.filterEmploye.as_view(), name = 'filtrar'),
    path('employe/<int:pk>', views.empleadoDetailView.as_view(), name = 'detail'),
    path('edit/<int:pk>/', views.EmpleadoUpdateView.as_view(), name = 'editar'),
    path('delete/<int:pk>', views.eliminar_empleado, name = 'eliminar'),
    path('crear/', views.EmpleadoCreateView.as_view(), name = 'crear'),
    path('email/',views.email, name = 'email')
]

aplications/departamento/models.py
from django.db import models

# Create your models here.

class Departamento(models.Model):
    # Campo nombre atributo unique hace que no se puedan agregar registros duplicados
    name = models.CharField('Nombre', max_length=50, unique= True)

    # el blank hace que deje pasar ese valor en blanco pero el resto no
    short_name = models.CharField('Nombre Corto', max_length=20, blank= True)
    active = models.BooleanField('Activo', default= False)


    # CLASE META, PARA PERSONALIZAR COMO SE VE EL MODELO EN EL ADMINISTRADOR DE DJANGO

    
    class Meta:
        verbose_name = 'Mi departamento' 
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['name'] # Ordena los registros por el nombre en orden alfabetico.

        """
            unique_together 
            no permite que se registren mas registros que tengan igual la combinancion de name y short_name, 
            los compara con los que estan en la base de datos y si encuentra alguno igual, no lo deja registrar

        """
        unique_together = ('name', 'short_name')

    def __str__(self) -> str:
        # return f'{self.name} - {self.short_name} - {str(self.active)}'
        return f'{self.name}'

aplications/departamento/views.py
from typing import Any
from django.db.models.query import QuerySet
from .models import Departamento
from aplications.empleados.models import Empleado
from django.shortcuts import render
from django.views.generic import (
    TemplateView,
    ListView,
    DeleteView,
    DetailView
)
# Create your views here.



class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/departamentos.html"
    context_object_name = 'departamentos'



class EmpleadoDetailListView(ListView):
    template_name = "departamento/listAll.html"
    context_object_name = 'empleados'
    def get_queryset(self):
        # print(self.kwargs)
        entrada = self.kwargs['dep']
        lista = Empleado.objects.filter(
            departamento__name = entrada
        )
        print(f'{lista}')
        return lista

templates/departamento/departamentos.html
{% extends 'base.html' %}
{% load static %}
<!-- Bloque que define el titulo  -->
{% block titulo %}
    Home
{% endblock titulo %}


<!-- Bloque que trae el cuerpo  -->
{% block body %}
    
{% include 'includes/nav.html' %}




<div class="container px-4 py-5">
    <h2>Dale <strong>click</strong> a un area para ver sus empleados</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-4">      
        {% for e in departamentos  %}
            <div class="card border-dark mb-3 mx-3" style="max-width: 18rem;">
                <div class="card-header">{{e.name}}</div>
                <div class="card-body text-dark">
                    <h5 class="card-title">{{e.short_name}}</h5>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores veritatis cumque, molestias enim, autem excepturi nulla.</p>
                    <a href="{% url 'departamento_app:detail_dep' e.name %}">
                        <button type="button" class="btn btn-outline-info">Ver personal</button>

                    </a>
                </div>
            </div>
            
        {% endfor %}
    </div>
</div>


{% include 'includes/footer.html' %}


{% endblock body %}

templates/departamento/listAll.html
{% extends 'base.html' %}
{% load static %}
<!-- Bloque que define el titulo  -->
{% block titulo %}
    All
{% endblock titulo %}

<!-- Bloque que trae el cuerpo  -->
{% block body %}
    
    {% include 'includes/nav.html' %}




<section class="mb-5">
    <div class="container mt-5">
        <h2>Empleados</h2>
        <!-- <div class="" style="width: fit-content;">
            <form class="form-inline d-flex" action="{% url 'persona_app:filtrar' %}" method="GET">
                {% csrf_token %}
                <div class="form-group mb-2">
                  <input type="text"  class="form-control" id="kword" name="kword" placeholder="Busca un empleado">
                </div>
                <button type="submit" class="btn btn-success mb-2 mx-3">Buscar</button>
            </form>
            
        </div> -->
        <table class="table table-bordered table-auto">
            <thead>
                <tr class="text-center">
                    <th> id </th>
                    <th> Name </th>
                    <th> Last Name </th>
                    <th> Department </th>
                    <th>
                         Accion 
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for empleado in empleados %}
                <tr>
                    <td>{{ empleado.id }}</td>
                    <td>{{ empleado.first_name }}</td>
                    <td>{{ empleado.apellidos }}</td>
                    <td>{{ empleado.departamento }}</td>
                    <td class="" style="width: 80px;"> 
                        <div class="d-flex justify-content-betwen align-items-center">
                            <div class="px-1">
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter{{ empleado.id }}">
                                    Eliminar
                                </button>
                                <!-- modal  -->                              
                                <div class="modal fade" id="exampleModalCenter{{ empleado.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Confirmar eliminación</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            ¿Estás seguro de que deseas eliminar a {{ empleado.first_name }}?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                            <form action="{% url 'persona_app:eliminar' empleado.id %}" method="POST">
                                                {% csrf_token %}                                               
                                                <button type="submit" class="btn btn-danger">Eliminar</button>
                                                
                                            </form>
                                        </div>
                                        </div>
                                    </div>
                                </div>                               
                            </div>

                        </div>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="2">No hay datos disponibles.</td>
                </tr>

                    
                {% endfor %}
            </tbody>
        </table>
        <!-- Paginador -->
        
        {% if is_paginated %}
            
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    
                    {% if page_obj.has_previous %}
                        
                        <li class="page-item ">
                            <a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1">Previous</a>
                        </li>
                        
                    {% endif %}

                    
                    {% for pagina in paginator.page_range %}
                        
                        {% if pagina == page_obj.number  %} 
                            
                            <li class="page-item"><a class="page-link active" href="?page={{pagina}}">{{pagina}}</a></li>  
                        {% else %}
                            <li class="page-item"><a class="page-link " href="?page={{pagina}}">{{pagina}}</a></li>  
                        {% endif %}
                            
                        
                    {% endfor %}
                        
                    
                    {% if page_obj.has_next %}
                        
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
                        </li>
                    {% endif %}
                        
                </ul>
            </nav>
        {% endif %}
            
    </div>
</section>

<!-- MODAL  -->

  
<!-- Modal -->








<section>
    {% include 'includes/footer.html' %}
</section>


{% endblock body %}
    