CRUD_EMPLEADOS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplications.empleados.urls')),
    path('', include('aplications.departamento.urls')),
    path('', include('aplications.home.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplications/empleados/urls.py
from django.urls import path
from . import views

app_name = "persona_app"



urlpatterns = [
    path('', views.Home_page.as_view(), name = 'home'),
    path('all/',views.listAll.as_view() ,name='list_all'),
    path('filter-Employe/', views.filterEmploye.as_view(), name = 'filtrar'),
    path('employe/<int:pk>', views.empleadoDetailView.as_view(), name = 'detail'),
    path('edit/<int:pk>/', views.EmpleadoUpdateView.as_view(), name = 'editar'),
    path('delete/<int:pk>', views.eliminar_empleado, name = 'eliminar'),
    path('crear/', views.EmpleadoCreateView.as_view(), name = 'crear'),
    path('email/',views.email, name = 'email')
]

aplications/empleados/models.py
from django.db import models
from aplications.departamento.models import Departamento

# Create your models here.

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length= 20, unique= True)

    class Meta():
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habiidades Empleados'

    def __str__(self) -> str:
        return f'{self.id} - {self.habilidad}'




class Empleado(models.Model):
    """Modelo para tabla empleado"""
    first_name = models.CharField('Nombre', max_length=60)
    apellidos = models.CharField('Apellidos', max_length=60)

    """Atributo seleccionable"""
    
    job_choices = (
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('3', 'Otro'),
        ('4', 'Secretaria'),
        ('5', 'Servicios Generales'),
        ('6', 'Practicante Universitario'),
        ('7', 'Coordinador'),

    )
    job = models.CharField('Trabajo', max_length= 1, choices= job_choices)

    """"""""""""""""""""""""""""""""""""

    """  Atrubuto que esta relacionado con otra tabla por una foreign key  """

    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)

    full_name = models.CharField('Nombre completo', max_length= 120, blank = True)

    """"""""""""""""""""""""""""""""""""

    image = models.ImageField('imagen', upload_to= 'empleados/', height_field=None, width_field=None, max_length=None, blank = True)

    ## Relacion de Muchos a Muchos ##

    habilidades = models.ManyToManyField(Habilidades)


    class Meta:
        verbose_name = 'Mi Empleado' 
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['-first_name','apellidos'] 


    def __str__(self) -> str:
        return f'{self.first_name} - {self.apellidos} - {self.job} - {self.image}'

aplications/empleados/forms.py
from django import forms

from aplications.departamento.models import Departamento
from .models import Empleado, Habilidades

class EmpleadoForm(forms.ModelForm):
    """Form definition for Empleado."""
    first_name = forms.CharField(widget = forms.TextInput(attrs = {'class': 'form-control'}))

    apellidos = forms.CharField(widget = forms.TextInput(attrs = {'class': 'form-control'}))

    job = forms.ChoiceField(label = 'Trabajo', choices = Empleado.job_choices, widget = forms.Select(attrs = {'class': 'form-control'}))

    departamento = forms.ModelChoiceField(
        queryset=Departamento.objects.all(),
        label='Departamento',
        widget=forms.Select(attrs={'class': 'form-control'}),  # Agrega clases de Bootstrap
    )


    habilidades = forms.ModelMultipleChoiceField(
        queryset=Habilidades.objects.all(),
        label='Habilidades',
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}),  # Agrega clases de Bootstrap
    )

    image = forms.ImageField(
        required=False,  # Para permitir dejar el campo vacío
        label='Imagen',
        widget=forms.ClearableFileInput(attrs={'class': 'custom-file-input'}),  # Agrega clases de Bootstrap
    )

    

    class Meta:
        """Meta definition for Empleadoform."""

        model = Empleado
        fields = ['first_name','apellidos','job','departamento','habilidades', 'image']


class RegisterForm(forms.ModelForm):

    """Form definition for Empleado."""
    first_name = forms.CharField(widget = forms.TextInput(attrs = {'class': 'form-control'}))

    apellidos = forms.CharField(widget = forms.TextInput(attrs = {'class': 'form-control'}))

    job = forms.ChoiceField(label = 'Trabajo', choices = Empleado.job_choices, widget = forms.Select(attrs = {'class': 'form-control'}))

    departamento = forms.ModelChoiceField(
        queryset=Departamento.objects.all(),
        label='Departamento',
        widget=forms.Select(attrs={'class': 'form-control'}),  # Agrega clases de Bootstrap
    )


    habilidades = forms.ModelMultipleChoiceField(
        queryset=Habilidades.objects.all(),
        label='Habilidades',
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}),  # Agrega clases de Bootstrap
    )

    image = forms.ImageField(
        required=False,  # Para permitir dejar el campo vacío
        label='Imagen',
        widget=forms.ClearableFileInput(attrs={'class': 'custom-file-input'}),  # Agrega clases de Bootstrap
    )

    class Meta:
        model = Empleado
        fields = ('__all__')


class getInTouch(forms.Form):

    name = forms.CharField(label="name", required=True,widget = forms.TextInput(attrs = {'class': 'form-control'}))
    subject = forms.CharField(label="subject", required=True,widget = forms.TextInput(attrs = {'class': 'form-control'}))
    email = forms.EmailField(label="Correo", required=True,widget = forms.TextInput(attrs = {'class': 'form-control'}))
    mensaje = forms.CharField(label="Mensaje", widget=forms.Textarea(attrs = {'class': 'form-control form-control-sm custom-textarea'}))

aplications/empleados/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.conf import settings
from aplications.departamento.models import Departamento
from .models import Empleado, Habilidades
from django.shortcuts import (render,get_object_or_404, redirect)
from django.core.mail import send_mail
from .forms import (
    EmpleadoForm,
    RegisterForm,
    getInTouch
)
from django.views.generic import (
    TemplateView,
    ListView,
    DeleteView,
    DetailView,
    UpdateView,
    CreateView
)
# Create your views here.

# class Home_page(TemplateView):
#     """Vista que carga la pagina de inicio"""
#     template_name = 'inicio.html'


class Home_page(ListView):
    model = Departamento
    context_object_name = 'areas'
    template_name = 'inicio.html'

    """Pasar una variable a mi template"""

    
    def get_context_data(self, **kwargs):
        context = super(Home_page, self).get_context_data(**kwargs)

        obj = [
            {
                'title': 'Area Contable',
                'direccion': 'static/img/carrusel1.jpg'
            },
            {
                'title': 'Gerencia',
                'direccion': 'static/img/carrusel2.png'
            },
            {
                'title': 'TI',
                'direccion': 'static/img/carrusel3.jpg'
            },
            {
                'title': 'Otro',
                'direccion': 'static/img/imagen1.jpg'
            },
            {
                'title': 'Area Contable',
                'direccion': 'static/img/imagen2.jpg'
            },
            {
                'title': 'Area Contable',
                'direccion': 'static/img/imagen3.jpg'
            },
        ]

        # Agrega tu formulario al contexto
        context['formulario'] = getInTouch()  # Reemplaza MiFormulario con el nombre de tu formulario

        context['imagenes'] = obj


        return context
    
class listAll(ListView):
    model = Empleado
    template_name = 'empleado/listAll.html'
    context_object_name = 'empleados'
    paginate_by = 6
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agrega un print para ver los datos que se están pasando al contexto
        print(context['empleados'])
        return context
    
    
"""
    Obtenemos el valor de la caja de texto para filtar un empleado

"""

class filterEmploye(ListView):
    template_name = 'empleado/listAll.html'
    context_object_name = 'empleados'
    paginate_by = 4
    def get_queryset(self):
        entrada = self.request.GET.get('kword')
        lista = Empleado.objects.filter(
            first_name__icontains = entrada
        )
        # print(lista)
        return lista
    

class empleadoDetailView(DetailView):
    ## Traemos el empleado ##
    model = Empleado
    template_name = 'empleado/detail.html'
    context_object_name = 'empleado'

    ## Traemos las habilidades
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        skils = Habilidades.objects 
        context['skills'] = Habilidades.objects.filter(empleado=self.object)

        
        return context
    


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "empleado/actualizar.html"
    # fields = ['first_name','apellidos','job','departamento','habilidades']
    form_class = EmpleadoForm
    success_url = reverse_lazy('persona_app:list_all')



# class EmpleadoDeleteView(DeleteView):
#     model = Empleado
#     template_name = "empleado/eliminar.html"
#     success_url = reverse_lazy('persona_app:list_all')


def eliminar_empleado(request, pk):
    empleado = get_object_or_404(Empleado, id=pk)
    print(f'------------ {empleado}-------{request}')
    
    if request.method == 'POST':
        empleado.delete()
        return redirect('departamento_app:departamentos')
    
    return redirect('persona_app:list_all')  # Redirigir en caso de que la solicitud no sea POST




class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "empleado/crear.html"
    form_class = RegisterForm

    success_url = reverse_lazy('persona_app:list_all')
    
    def form_valid(self, form: RegisterForm) -> HttpResponse:
        """
            Aca entra cuando los datos ya estan validos y guardados en la base de datos

        """

        #Logica del proceso
        empleado = form.save(commit= False)
        empleado.full_name = empleado.first_name + ' ' +empleado.apellidos
        empleado.save()

        return super().form_valid(form)


def email( request ):

    if (request.method == 'POST'):

        form = getInTouch(request.POST)
        if form.is_valid():
            # El formulario es válido, haz algo con los datos aquí, por ejemplo, enviar un correo electrónico
            # form.cleaned_data contiene los datos del formulario validados
            # Envía un correo electrónico aquí si es necesario
            # Redirecciona a una página de éxito o muestra un mensaje de éxito.
            datos_formulario = form.cleaned_data
            print(datos_formulario)
            recipient_list = ['nicovalbuena2011@gmail.com']

            send_mail(datos_formulario['subject'], datos_formulario['mensaje'], datos_formulario['email'], recipient_list)

            return redirect('persona_app:home')
        else:
            print(f'Formulario invalido---')
            # Si la solicitud no es un POST, simplemente muestra el formulario en blanco
            form = getInTouch()
    
            return render(request, 'inicio.html', {'form': form})

 

        
        
    
    





    

    

    
    
    
    

templates/empleado/actualizar.html
{% extends 'base.html' %}
{% load static %}
<!-- Bloque que define el titulo  -->
{% block titulo %}
    All
{% endblock titulo %}

<!-- Bloque que trae el cuerpo  -->
{% block body %}
    
{% include 'includes/nav.html' %}

<div class="mx-5 p-5">

  <form class=" border rounded border-secondary  p-4" style=" width: 500px;" method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    <div class="form-group">
      <label for="formGroupExampleInput">Nombres</label>
      <!-- <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input"> -->
      {{form.first_name}}
    </div>
    <div class="form-group py-2">
      <label for="formGroupExampleInput2">Apellidos</label>
      <!-- <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input"> -->
      {{form.apellidos}}
    </div>
    <div class="form-group">
      <label for="formGroupExampleInput2">Trabajo</label>
      <!-- <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input"> -->
      {{form.job}}
    </div>
    <div class="form-group py-2">
      <label for="formGroupExampleInput2">Departamento</label>
      <!-- <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input"> -->
      {{form.departamento}}
    </div>
    <div class="form-group">
      <label for="formGroupExampleInput2">Habilidades</label>
      <!-- <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input"> -->
      {{form.habilidades}}
    </div>
    <div class="mt-2 custom-file">
      {{ form.image }}
      <!-- <label class="custom-file-label" for="{{ form.image.id_for_label }}">Choose file</label> -->
    </div>
    <button type="submit" class=" mt-3 btn btn-primary">Actualizar</button>
  </form>
</div>




  



<section>
    {% include 'includes/footer.html' %}
</section>


{% endblock body %}

templates/empleado/crear.html
{% extends 'base.html' %}
{% load static %}
<!-- Bloque que define el titulo  -->
{% block titulo %}
    All
{% endblock titulo %}

<!-- Bloque que trae el cuerpo  -->
{% block body %}
    
    {% include 'includes/nav.html' %}

    <div class="container d-flex justify-content-center align-items-center p-5 ">
        <div class="col-12 col-md-6 col-lg-4 card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Registra un Empleado</h4>
                </div>
                <form action="" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="nombre" class="form-label">Nombre</label>
                        {{form.first_name}}

                    </div>
                    <div class="mb-3">
                        <label for="nombre" class="form-label">apellidos</label>
                        {{form.apellidos}}

                    </div>
                    <div class="mb-3">
                        <label for="nombre" class="form-label">Trabajo</label>
                        {{form.job}}

                    </div>
                    <div class="mb-3">
                        <label for="nombre" class="form-label">Departamento</label>
                        {{form.departamento}}

                    </div>
                    <div class="mb-3">
                        <label for="nombre" class="form-label"><strong>Habilidades</strong> ctrl + click para añadir varias</label>
                        {{form.habilidades}}

                    </div>
                    <div class="mb-3">
                        <label for="nombre" class="form-label">Imagen</label>
                        {{form.image}}

                    </div>
                    <!-- my_template.html -->
                    <!-- <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                    </div> -->
                    <div>
                        <button type="submit" class="btn btn-success" style="width: 100%;" data-toggle="modal" data-target="#successModal">Registrar</button>
                    </div>

                </form>
            </div>
        </div>
    </div>

    <!-- Modal de éxito -->
    <div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="successModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="successModalLabel">Registro Exitoso</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ¡El empleado se ha registrado exitosamente!
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>



    <section>
        {% include 'includes/footer.html' %}
    </section>
<!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        // Escucha cambios en los campos del formulario y actualiza la barra de progreso
        $('input, select, textarea').on('input', function() {
        // Calcula el progreso basado en el número de campos completados
        var totalCampos = $('input, select, textarea').length;
        var camposCompletados = $('input:valid, select:valid, textarea:valid').length;
        var progreso = (camposCompletados / totalCampos) * 100;
    
        // Actualiza la barra de progreso
        $('.progress-bar').css('width', progreso + '%').attr('aria-valuenow', progreso);
        });
    });
</script> -->
    
    
{% endblock body %}
        

templates/empleado/detail.html
{% extends 'base.html' %}
{% load static %}
<!-- Bloque que define el titulo  -->
{% block titulo %}
    All
{% endblock titulo %}

<!-- Bloque que trae el cuerpo  -->
{% block body %}
    
    {% include 'includes/nav.html' %}

    <section>
        <div class="container">

            <div class="row mt-5">
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="card" style="width: 18rem;">
                        
                        {% if empleado.image  %}
                            <img class="card-img-top" src="{% static 'img/'|add:empleado.first_name|add:'.jpg' %}" alt="Card image cap">
                        {% else %}
                            <img class="card-img-top" src="{% static 'img/unknow.jpg' %}" alt="Card image cap">
                        {% endif %}
                        <div class="card-body">
                          <h5 class="card-title"><strong>{{empleado.first_name}}  {{empleado.apellidos}}</strong></h5>
                          <p class="card-text">
                              <h6>{{empleado.get_job_display}} - {{empleado.departamento}}</h6>
                              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Esse fuga saepe voluptatibus.
                          </p>
                          <div class="">
                                <a href="{% url 'persona_app:list_all' %}" class="btn btn-primary">Go back</a>
                                <a href="{% url 'persona_app:editar' empleado.id %}" class="btn btn-warning">Editar</a>
                          </div>
                        </div>
                    </div>
                    
                    
                </div>
                <div class="col-12 col-md-6 col-lg-4">

                    <div class="" style="margin-left: 40px;">
                        <h2>Calificación</h2>
                        <img style="width: 60px; margin-right: 10px;" src="{% static 'img/medal.webp' %}" alt="">
                        <img style="width: 60px; margin-right: 10px;" src="{% static 'img/medal.webp' %}" alt="">
                        <img style="width: 60px; margin-right: 10px;" src="{% static 'img/medal.webp' %}" alt="">
                        <img style="width: 60px; margin-right: 10px; filter: grayscale(100%);" src="{% static 'img/medal.webp' %}" alt="">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. </p>
        
                        <h3>Habilidades</h3>
                        <div class="">
                            
                            {% for e in skills  %}
                                <li>
                                    {{e.habilidad}}
                                    <div class="progress">
                                        <div class="progress-bar bg-success" role="progressbar" style="width: 75%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </li>
                            {% endfor %}
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </section>



    

    <section>
        {% include 'includes/footer.html' %}
    </section>


{% endblock body %}

templates/empleado/eliminar.html
<h2>eliminando</h2>

templates/empleado/listAll.html
{% extends 'base.html' %}
{% load static %}
<!-- Bloque que define el titulo  -->
{% block titulo %}
    All
{% endblock titulo %}

<!-- Bloque que trae el cuerpo  -->
{% block body %}
    
    {% include 'includes/nav.html' %}


    <section class="mb-5">
        <div class="container mt-5">
            <h2>Empleados</h2>
            <div class="" style="width: fit-content;">
                <form class="form-inline d-flex" action="{% url 'persona_app:filtrar' %}" method="GET">
                    {% csrf_token %}
                    <div class="form-group mb-2">
                      <input type="text"  class="form-control" id="kword" name="kword" placeholder="Busca un empleado">
                    </div>
                    <button type="submit" class="btn btn-success mb-2 mx-3">Buscar</button>
                </form>
                
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr class="text-center">
                        <th> id </th>
                        <th> Name </th>
                        <th> Last Name </th>
                        <th> Department </th>
                        <th> Accion </th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                    <tr>
                        <td>{{ empleado.id }}</td>
                        <td>{{ empleado.first_name }}</td>
                        <td>{{ empleado.apellidos }}</td>
                        <td>{{ empleado.departamento }}</td>
                        <td class="text-center"> 
                            <a href="{% url 'persona_app:detail' empleado.id %}">
                                <button type="button" class="btn btn-info">Info</button>     
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="2">No hay datos disponibles.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <!-- Paginador -->
            
            {% if is_paginated %}
                
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        
                        {% if page_obj.has_previous %}
                            
                            <li class="page-item ">
                                <a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1">Previous</a>
                            </li>
                            
                        {% endif %}

                        
                        {% for pagina in paginator.page_range %}
                            
                            {% if pagina == page_obj.number  %} 
                                
                                <li class="page-item"><a class="page-link active" href="?page={{pagina}}">{{pagina}}</a></li>  
                            {% else %}
                                <li class="page-item"><a class="page-link " href="?page={{pagina}}">{{pagina}}</a></li>  
                            {% endif %}
                                
                            
                        {% endfor %}
                            
                        
                        {% if page_obj.has_next %}
                            
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
                            </li>
                        {% endif %}
                            
                    </ul>
                </nav>
            {% endif %}
                
        </div>
    </section>

    <section>
        {% include 'includes/footer.html' %}
    </section>


{% endblock body %}